# Azure Pipelines for HW8 ingestion (Windows agent, robust path detection)
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  # Show repo layout (debug)
  - powershell: |
      Write-Host "Repo root: $(Build.SourcesDirectory)"
      Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Depth 2 | Select-Object FullName
    displayName: 'List files (debug)'

  # Install Microsoft ODBC Driver 18 for SQL Server (x64) via MSI
  - powershell: |
      $ErrorActionPreference = "Stop"
      $url = "https://go.microsoft.com/fwlink/?linkid=2290265"  # msodbcsql18 x64
      $msi = "$(Agent.TempDirectory)\msodbcsql18.msi"
      Invoke-WebRequest -Uri $url -OutFile $msi
      Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qn IACCEPTMSODBCSQLLICENSETERMS=YES ADDLOCAL=ALL" -Wait -NoNewWindow
      Write-Host "ODBC 18 installed."
    displayName: 'Install ODBC Driver 18 (MSI)'

  # Install Python deps (auto-detect requirements.txt path)
  - powershell: |
      $root = "$(Build.SourcesDirectory)"
      $candidates = @(
        Join-Path $root "HW8\requirements.txt",
        Join-Path $root "requirements.txt"
      )
      $req = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
      if (-not $req) { throw "requirements.txt not found. Looked at: $($candidates -join ', ')" }
      Write-Host "Using requirements: $req"
      python -m pip install --upgrade pip
      pip install -r "$req"
    displayName: 'Install Python deps (auto-detect)'

  # Run ingestion (auto-detect ingest.py path)
  - powershell: |
      $root = "$(Build.SourcesDirectory)"
      $candidates = @(
        Join-Path $root "HW8\ingest.py",
        Join-Path $root "ingest.py"
      )
      $script = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
      if (-not $script) { throw "ingest.py not found. Looked at: $($candidates -join ', ')" }
      Write-Host "Running: $script"
      python "$script"
    displayName: 'Run ingestion (auto-detect)'
    env:
      AZURE_SQL_SERVER: hwdbms.database.windows.net
      AZURE_SQL_DATABASE: hwdbms
      AZURE_SQL_USER: hwdbms
      AZURE_SQL_PASSWORD: $(AZURE_SQL_PASSWORD)
