# Azure Pipelines for HW8 ingestion (Windows agent, ODBC via MSI)
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'

  # Install Microsoft ODBC Driver 18 for SQL Server (x64) via MSI (reliable in CI)
  - powershell: |
      $ErrorActionPreference = "Stop"
      $url = "https://go.microsoft.com/fwlink/?linkid=2290265"  # msodbcsql18 x64
      $msi = "$(Agent.TempDirectory)\msodbcsql18.msi"
      Write-Host "Downloading ODBC 18 from $url ..."
      Invoke-WebRequest -Uri $url -OutFile $msi
      Write-Host "Installing ODBC 18 ..."
      Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qn IACCEPTMSODBCSQLLICENSETERMS=YES ADDLOCAL=ALL" -Wait -NoNewWindow
      Write-Host "ODBC 18 installed."
    displayName: 'Install ODBC Driver 18 (MSI)'

  # (Optional) Install sqlcmd/bcp tools for debugging in CI
  # - powershell: |
  #     $ErrorActionPreference = "Stop"
  #     $url = "https://go.microsoft.com/fwlink/?linkid=2187333"  # MsSqlCmdLn18.msi
  #     $msi = "$(Agent.TempDirectory)\MsSqlCmdLn18.msi"
  #     Invoke-WebRequest -Uri $url -OutFile $msi
  #     Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qn IACCEPTMSSQLTOOLSLICENSETERMS=YES ADDLOCAL=ALL" -Wait -NoNewWindow
  #     Write-Host "sqlcmd installed."
  #   displayName: 'Install SQL Server Command Line Tools (optional)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r HW8/requirements.txt
    displayName: 'Install Python deps'

  - script: |
      python HW8/ingest.py
    displayName: 'Run ingestion'
    env:
      AZURE_SQL_SERVER: hwdbms.database.windows.net
      AZURE_SQL_DATABASE: hwdbms
      AZURE_SQL_USER: hwdbms
      AZURE_SQL_PASSWORD: $(AZURE_SQL_PASSWORD)
